### PR TITLE
Energy Decomposition Analysis adopted for general MCSCF 

### PR DESCRIPTION
**Pull request by JangidBhavnesh**
Previously EDA is hardcoded for the CASSCF wavefunction only. I added the functionality to do this analysis for the DMRG-PDFT as well.

### CODE REVIEW

**Comment by matthew-hennefarth** [comment]
LGTM. Do you know if any of the tests actually test this feature? Perhaps we could add one if not.

**Comment by JangidBhavnesh** [comment]
We don't have any test for this functionality. 

I will add a unit test. Here, the sum of EDA components would be equal to the MCPDFT energy for the given state.

**Comment by matthew-hennefarth** [comment]
> Here, the sum of EDA components would be equal to the MCPDFT energy for the given state.

Not necessarily, I believe. Doesn't it also include more than just the Coulomb interaction, such as CAS exchange? As in `e_ncwfn` includes full 2e active space contribution if I read the code correctly. Also, for hybrid funcs it might disagree.

**Comment by JangidBhavnesh** [comment]
Sorry, there is a test for energy_decomposition. Though, whatever I have changed is passing the test.
https://github.com/pyscf/pyscf-forge/blob/master/pyscf/mcpdft/test/test_mcpdft.py

Also, energy_decomposition is not implemented for the hybrid functionals. 
https://github.com/pyscf/pyscf-forge/blob/master/pyscf/mcpdft/mcpdft.py#L274

However, it won't be that difficult to implement it. It can be represented as
$E_{OT} = \lambda (\frac{1}{2}g_{pqrs}D_{pqrs}) + (1-\lambda ) E[\rho, \Pi]$
Where it can further be decomposed into exchange and correlation.

**Comment by JangidBhavnesh** [comment]
> Not necessarily, I believe. Doesn't it also include more than just the Coulomb interaction, such as CAS exchange? As in `e_ncwfn` includes full 2e active space contribution if I read the code correctly. Also, for hybrid funcs it might disagree.

Yes, you are right. MCPDFT energy doesn't include the e_ncwfn. 
$E_{MCPDFT} = sum(E_{Decomposition}[:3  or  :4])$ (depends on split_xc)

**Comment by matthew-hennefarth** [comment]
> However, it won't be that difficult to implement it. It can be represented as E O T = λ ( 1 2 g p q r s D p q r s ) + ( 1 − λ ) E [ ρ , Π ] Where it can further be decomposed into exchange and correlation.

You don't have to even do that. The MC-PDFT energy should actually be $E^{PDFT} = E^{1e} + Coul + \lambda E^{ncwfn} + (1-\lambda)E^{ot}$. If $\lambda = 0$, it will still work.

**Review by MatthewRHermes — APPROVED** [review]
Thanks for cleaning up my old spaghetti!

**Pull request merged**
